### ISSUE TITLE
Opts Settings for remote database

### ISSUE THREAD

**Issue by FHBI-Raphael** [nukedzn/node-informix#46]
Hi,
i need help with opts settings for a remote database! I tried many combinations of database-options but nothing works!

I need the option settings (opts) for the following odbc connection string:
`jdbc:informix-sqli://192.168.32.15:1630/myDatabase:INFORMIXSERVER=myServer`

What should i insert into the opts instead of the following informations:
_var opts = {
  database : '192.168.32.15:1630/myDatabase@myServer',
  username : 'myDatabaseUser',
  password : 'myDatabasePassword'
};_

Any help?

**Comment by uditha-atukorala** [comment]
You can only specify `[database]@[dbservername]` in opts and your host and port details should be configured in [sqlhosts](https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.admin.doc/ids_admin_0152.htm) entries.

There's an Informix GUI tool for Windows to set SQLHOSTS registry key entries and for Unix systems it is just a text file (defaults to `${INFORMIXDIR}/etc/sqlhosts`). See [sqlhosts connectivity information](https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.admin.doc/ids_admin_0161.htm) for more info. 

Here's a basic example sqlhosts file:
```
# IANA (www.iana.org) assigned port number/service names for Informix:
# sqlexec 9088/tcp
# sqlexec-ssl 9089/tcp

ol_informix1210 onsoctcp 10.0.0.1 sqlexec
```

**Comment by FHBI-Raphael** [comment]
My state of not knowing the informix database caused the problem.

These informations worked for me:
`var opts = {
database : 'myDatabase@myServer',
username : 'myDatabaseUser',
password : 'myDatabasePassword'
};`
where my sqlhosts file looked like:
`myServer onsoctcp 192.168.32.15 1630`

Thank you for your help!!! This solved my problem!!!
