### ISSUE TITLE
JSON column not working.

### ISSUE THREAD

**Issue by PawarPawan** [nukedzn/node-informix#51]
Hi team, I created a table with json column, I have inserted data into that table successfully using dbaacess tool of informix, but when I am trying to insert data into table using ifxnjs package prepared query, It give me error like this

User Defined Routine error. sqlerrm(json_in)[U0000]JSON

can any one please help me resolve this issue?

**Comment by uditha-atukorala** [comment]
Could you please give an example? `CREATE TABLE` and a JS code sample would help to look into things quicker.

**Comment by uditha-atukorala** [comment]
No response from OP for over a month, I'm closing this.
