### ISSUE TITLE
Build Issue on Ubuntu linux

### ISSUE THREAD

**Issue by ajozz13** [nukedzn/node-informix#52]
Hello,
After attempting to build ( **npm install --save informix** )  
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

@node-base:~$ node -v
v9.3.0
@node-base:~$ npm -v
5.6.0
@node-base:~$ 

I got the error result:
gyp: Call to 'THREADLIB=POSIX esql -thread -libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-92-generic

Here is the log excert:
215 verbose lifecycle informix@0.5.9~install: unsafe-perm in lifecycle true
216 verbose lifecycle informix@0.5.9~install: PATH: /usr/local/lib/node_modules/
npm/node_modules/npm-lifecycle/node-gyp-bin:/home/aochoa/services/dbtest/node_mo
dules/informix/node_modules/.bin:/home/aochoa/services/dbtest/node_modules/.bin:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/aochoa/apps/I
BM/informix/bin
217 verbose lifecycle informix@0.5.9~install: CWD: /home/aochoa/services/dbtest/node_modules/informix
218 silly lifecycle informix@0.5.9~install: Args: [ '-c', 'node-gyp rebuild' ]
219 silly lifecycle informix@0.5.9~install: Returned: code: 1  signal: null
220 info lifecycle informix@0.5.9~install: Failed to exec install script
221 verbose unlock done using /home/aochoa/.npm/_locks/staging-b3a1fe030de2c206.lock for /home/aochoa/services/dbtest/node_modules/.staging
222 silly saveTree dbtest@1.0.0
222 silly saveTree └─┬ informix@0.5.9
222 silly saveTree   ├── bindings@1.3.0
222 silly saveTree   ├─┬ debug@3.1.0
222 silly saveTree   │ └── ms@2.0.0
222 silly saveTree   ├── moment@2.20.1
222 silly saveTree   ├── nan@2.8.0
223 warn dbtest@1.0.0 No description
224 warn dbtest@1.0.0 No repository field.
225 verbose stack Error: informix@0.5.9 install: `node-gyp rebuild`
225 verbose stack Exit status 1
225 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
225 verbose stack     at EventEmitter.emit (events.js:159:13)
225 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
225 verbose stack     at ChildProcess.emit (events.js:159:13)
225 verbose stack     at maybeClose (internal/child_process.js:943:16)
225 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
226 verbose pkgid informix@0.5.9
227 verbose cwd /home/aochoa/services/dbtest
228 verbose Linux 4.4.0-92-generic
229 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "informix"
230 verbose node v9.3.0
231 verbose npm  v5.6.0
232 error code ELIFECYCLE
233 error errno 1

**Comment by uditha-atukorala** [comment]
Do you have [IBM Informix CSDK](http://www-03.ibm.com/software/products/en/csdk) installed and [esql patch](https://github.com/nukedzn/node-informix/blob/master/esql-4.10.debian.patch) applied? 

If you run ` THREADLIB=POSIX esql -thread -libs` in a terminal, what's the output you get?

**Comment by ajozz13** [comment]
aochoa@node-base:~$ THREADLIB=POSIX esql -thread -libs
esql:   When using -thread, the THREADLIB environment variable
	must be set to a supported thread library. Currently
	supporting: DCE, POSIX(HP-UX 11.0, Solaris 2.5 and higher only) and
	SOL (Solaris Kernel Threads).

**Comment by ajozz13** [comment]
Thank you for the follow up..btw

**Comment by ajozz13** [comment]
aochoa@node-base:~/apps/IBM/informix/bin$ THREADLIB=POSIX esql -thread -libs
-lthsql
-lthasf
-lthgen
-lthos
-lifgls
-lpthread
-lm
-ldl
-lcrypt
/home/aochoa/apps/IBM/informix/lib/esql/checkapi.o
-lifglx
-lpthread

**Comment by ajozz13** [comment]
After ensuring the patch was applied I was able to get the the informix dependency installed.

**Comment by uditha-atukorala** [comment]
Glad it got sorted and sorry it took a bit of time to respond.
