### ISSUE TITLE
Prepared Statement error after completing a successful entry

### ISSUE THREAD

**Issue by ajozz13** [nukedzn/node-informix#53]
Hello,
I created a wrap function returning a promise that executes, captures a serial key after insertion.
and ends the context after each successful entry, however on a subsequent calls the following error message is captured;

Error: A Statement is already prepared with the same ID.
    at /home/aochoa/services/ibc_informix/node_modules/informix/lib/statement.js:176:16
    at new Promise (<anonymous>)
    at /home/aochoa/services/ibc_informix/node_modules/informix/lib/statement.js:171:11
    at <anonymous>

I understood that upon closing the context the prepared statement gets dismissed, is this correct?

here is the code of the wapper function

	this.contextStatement = function( qry, vals ){

		var serial = -1;
		return new Promise( ( resolve, reject ) => {
			var ctx = this.informix.createContext();
			ctx.begin()
			.then( function(){
				return ctx.prepare( qry );
			//	return ctx.prepare( "insert into users(username, full_name, station, clearance) values (?, ?, ?, ?)" );
			})
			.then( function( statement ){
				return statement.exec( vals );
			})
			.then( function( cursor ){
				serial = cursor.serial();
				cursor.close();
				return ctx.commit();
			})
			.then( function(){
				ctx.end();
				resolve( serial );
			})
			.catch( function( err ){
				reject( err );
			})
		});
	};

**Comment by uditha-atukorala** [comment]
Hi, 
No, prepared statements created within a context don't get dismissed when the context ends. The context is only used to tie the statement to a connection within the connection pool (so the transactions work properly).

Although, I agree when closing a context all prepared statements within that context should be freed as well. I'll take a look. 

Thanks for reporting this.

**Comment by ajozz13** [comment]
Thanks for checking...will statement free() call close the statement?

Regards
Alberto

**Comment by uditha-atukorala** [comment]
Yup, that'll do the trick.

**Comment by ajozz13** [comment]
Great...I'll try the functionality calling the free statement before
closing the context.
Regards
Alberto
