### ISSUE TITLE
How to call stored  procedure

### ISSUE THREAD

**Issue by aziotdev** [nukedzn/node-informix#65]
Can i know how to call stored procedure  of informix from this library.

Thank you.

**Comment by uatuko** [comment]
You can execute a stored proc like any other query. There's an example in tests ([test/lib.context.test.js#L64](https://github.com/nukedzn/node-informix/blob/ed39e82f877ff07f7976e54f38031a6eb8715708/test/lib.context.test.js#L64)).

**Comment by aziotdev** [comment]
Thank you!!

**Comment by aziotdev** [comment]
Thank you!!

**Comment by jayaruvan** [comment]
Thank you!!
